### ISSUE TITLE
Reconnect issue

### ISSUE THREAD

**Issue by piccotalent-127** [vsevex/echox#24]
Hello,
This plugin is working well for both Android And IOS 
but when I turn off the internet or when my internet suddenly cut off
and connected back echo is calling reconnect but it is not reconnecting sometimes it is giving reconnected but 
in ejjaberd admin the user is not showing and messages are not sent and recieved

By the way this plugin is very usefull

**Comment by vsevex** [comment]
hi, thank you for opening an issue. it is important for me to upgrade this package depending on your comments!

at the moment, I can not give support to the stable version due I am working on new structure and policies. it will be updated as soon as possible and reconnection mechanism will be updated as well.

good luck on your development.

**Comment by piccotalent-127** [comment]
Ok thank  you for your response also It would be best if you give examples for all the handlers available
